variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git"

cache:
  paths:
    - cache/

before_script:
  - mkdir -p cache
  - echo cache >>.Rbuildignore
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
  - echo "options(Ncpus = $(nproc --all))\n.libPaths(\"$PWD/cache\")" >> /usr/local/lib/R/etc/Rprofile.site
  - install2.r devtools
  - r -e 'devtools::install_dev_deps()'

r-release:
  stage: test
  tags:
    - docker
  image: rocker/r-ver:latest
  script:
    - r -e 'devtools::install_github("analytics-ufcg/rcongresso")'
    - Rscript -e 'stopifnot(length(devtools::check(check_dir = ".", args = c("--no-examples", "--as-cran", "--no-manual", "--no-tests"))$errors) == 0L)'
    - Rscript -e 'res=devtools::test(reporter="summary");df=as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'
    - Rscript -e 'library(covr);package_coverage()'
  artifacts:
    paths:
      - "*.Rcheck"
    name: logs
  when: always
    
pages:
  stage: deploy
  tags:
    - docker
  image: rocker/tidyverse:latest
  script:
    - install2.r pkgdown
    - r -e 'devtools::install_github("analytics-ufcg/rcongresso")'
    - r -e 'devtools::install()'
    - r -e 'devtools::document()'
    - r -e 'pkgdown::build_site(override = list(destination = "public"))'
    - ./scripts/build_all.R
    - mv docs public/
  artifacts:
    paths:
      - public
